package com.ray.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseRoles<M extends BaseRoles<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setRoleName(java.lang.String roleName) {
		set("role_name", roleName);
		return (M)this;
	}
	
	public java.lang.String getRoleName() {
		return getStr("role_name");
	}

	public M setRoleNickName(java.lang.String roleNickName) {
		set("role_nick_name", roleNickName);
		return (M)this;
	}
	
	public java.lang.String getRoleNickName() {
		return getStr("role_nick_name");
	}

}
