package com.ray.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseSysObject<M extends BaseSysObject<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setCode(java.lang.String code) {
		set("code", code);
		return (M)this;
	}
	
	public java.lang.String getCode() {
		return getStr("code");
	}

	public M setName(java.lang.String name) {
		set("name", name);
		return (M)this;
	}
	
	public java.lang.String getName() {
		return getStr("name");
	}

	public M setTableName(java.lang.String tableName) {
		set("table_name", tableName);
		return (M)this;
	}
	
	public java.lang.String getTableName() {
		return getStr("table_name");
	}

	public M setPkName(java.lang.String pkName) {
		set("pk_name", pkName);
		return (M)this;
	}
	
	public java.lang.String getPkName() {
		return getStr("pk_name");
	}

	public M setIsSingle(java.lang.Boolean isSingle) {
		set("is_single", isSingle);
		return (M)this;
	}
	
	public java.lang.Boolean getIsSingle() {
		return get("is_single");
	}

	public M setIsCelledit(java.lang.Boolean isCelledit) {
		set("is_celledit", isCelledit);
		return (M)this;
	}
	
	public java.lang.Boolean getIsCelledit() {
		return get("is_celledit");
	}

	public M setIsShowNum(java.lang.Boolean isShowNum) {
		set("is_show_num", isShowNum);
		return (M)this;
	}
	
	public java.lang.Boolean getIsShowNum() {
		return get("is_show_num");
	}

	public M setIsFirstLoad(java.lang.Boolean isFirstLoad) {
		set("is_first_load", isFirstLoad);
		return (M)this;
	}
	
	public java.lang.Boolean getIsFirstLoad() {
		return get("is_first_load");
	}

	public M setFilter(java.lang.String filter) {
		set("filter", filter);
		return (M)this;
	}
	
	public java.lang.String getFilter() {
		return getStr("filter");
	}

	public M setDefaultOrder(java.lang.String defaultOrder) {
		set("default_order", defaultOrder);
		return (M)this;
	}
	
	public java.lang.String getDefaultOrder() {
		return getStr("default_order");
	}

	public M setDiyCard(java.lang.String diyCard) {
		set("diy_card", diyCard);
		return (M)this;
	}
	
	public java.lang.String getDiyCard() {
		return getStr("diy_card");
	}

	public M setDiyJs(java.lang.String diyJs) {
		set("diy_js", diyJs);
		return (M)this;
	}
	
	public java.lang.String getDiyJs() {
		return getStr("diy_js");
	}

	public M setBizIntercept(java.lang.String bizIntercept) {
		set("biz_intercept", bizIntercept);
		return (M)this;
	}
	
	public java.lang.String getBizIntercept() {
		return getStr("biz_intercept");
	}

	public M setViewSql(java.lang.String viewSql) {
		set("view_sql", viewSql);
		return (M)this;
	}
	
	public java.lang.String getViewSql() {
		return getStr("view_sql");
	}

	public M setConfig(java.lang.String config) {
		set("config", config);
		return (M)this;
	}
	
	public java.lang.String getConfig() {
		return getStr("config");
	}

}
