package com.ray.common.model;

import com.ray.common.model.base.BaseGpProcode;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class GpProcode extends BaseGpProcode<GpProcode> {
	public static final GpProcode dao = new GpProcode().dao();
}
