package com.ray.common.model;

import com.ray.common.model.base.BasePermissions;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Permissions extends BasePermissions<Permissions> {
	public static final Permissions dao = new Permissions().dao();
}
