package com.ray.common.model;

import com.ray.common.model.base.BaseRoles;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Roles extends BaseRoles<Roles> {
	public static final Roles dao = new Roles().dao();
}
