package com.ray.common.model;

import com.ray.common.model.base.BaseSysObject;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SysObject extends BaseSysObject<SysObject> {
	public static final SysObject dao = new SysObject().dao();
}
